.TH "GFIFTEEN" 6 "5 APRIL 2012" "" ""
.SH NAME
\fBgFifteen \fP- sliding tile puzzle game
\fB
.SH SYNOPSIS
.nf
.fam C
\fBgfifteen\fP
.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
gFifteen is a graphical implementation of the old puzzle game Fifteen. The goal is to move the numbered tiles from a random starting position into the following arrangement, with the empty space at the bottom right:
.PP
  1  2  3  4
  5  6  7  8
  9 10 11 12
 13 14 15
.PP
You can only rearrange the tiles by moving a tile next to the empty space into the empty space. Simply click on a tile to move it. When you have solved the puzzle, gFifteen will show you how many moves you used to solve the puzzle, as well as how much time you used. All puzzles provided are solveable.
.PP
For additional challenge, attempt to complete each puzzle in as few moves as possible, or as quickly as possible. Bobby Fischer was known to have completed the puzzle in 25 seconds in a public demonstration. Using this software, which is a faster interface than a real board, it should be possible to complete it in less time.
.SH AUTHOR
Christopher Howard <christopher.howard@frigidcode.com>
